=== !

[source,javascript]
----

a = 1

b = a

----

[NOTE.speaker]
--
The other key way {cpp} type system differs from JavaScript, Java, C#, and they way it deals with values and references.
--

=== !

[source,python]
----

a = 1

b = a

b += 2

----

[NOTE.speaker]
--
(What language is this?  It's JavaScript, but could be more or less anything)

If we do this, what's the value of a and b?

So, here, a and b have value semantics. If I do something to a, b doesn't change and if I do something to b, a isn't affected.
--

=== !

[source,javascript]
----

a = [1, 2, 3, 4]

b = a

----

[NOTE.speaker]
--
What about now?
--

=== !

[source,javascript]
----

a = [1, 2, 3, 4]

b = a

b[1] = 99

----

[NOTE.speaker]
--
What about this? What do a and b look like now.

Here, they have reference semantics. a and b refer to the same object, somewhere off in memory.  If I perform some operation on the object, both a and b see that.

And we're comfortable with that, right. We see that same thing with other languages, Java, Python, C#, and so on.

Some types - boolean, integers, strings, often called the builtin types - behave like values, but everything else - objects, arrays, tuples, dicts - behave like references.

(C# structs have value sematics, the new Java records will too I think)
--

=== !

[source,cpp]
----

auto a = 1;

auto b = a;

b += 2;

----

[NOTE.speaker]
--
Same as before, right? a is 1 and b = 3.
--

=== !

[source,cpp]
----

auto a = std::vector<int> { 1, 2, 3, 4 };

auto b = a;

b[1] = 99;

----

[NOTE.speaker]
--
I've probably tipped my hand here, but any guesses?

b is a copy of a, so anything I do to b doesn't change a at all
--

=== !

[source,cpp]
----

auto a = std::vector<int> { 1, 2, 3, 4 };

auto& b = a;

b[1] = 99;

----

[NOTE.speaker]
--
And now?

Here, I've explicitly said I want a reference, so now b refers to a, and anything I do to b is actually happening to a.
--

=== !

[source,cpp]
----

auto a = 1;

auto& b = a;

b += 2;

----

[NOTE.speaker]
--
Ah, I can also apply reference semantics to built in types like integers.

So, in {cpp}, I can have both value semantics and reference semantics. They're not implicit in the thing I'm working with - I can choose, for whatever suits the situation best.

Notice that the choice of value or reference is separate from the declaration - it's not implicit in the thing, it's related to how you want to handle it. Need a copy - take a copy, need a reference - have a reference.

Is that all fairly clear?
--
