== {cpp}

What is C++?

== {cpp}

{cpp} is a general purpose programming language

* it is multi-paradigm

* compiled

* strongly typed

* statically typed

[NOTE.speaker]
--
Multi-paradigm - what to work in a functional style? Go ahead. Object-orientation? Fine.

Compiled - to machine code!

Strongly typed - constants and variables have a type, and that type ain't changing

Statically typed - those types are known at compile time

Do sing out with questions as we go. This whole thing will be better if you do. I'm a decent hand at {cpp}, but one of the ways we learn is by teaching. There are, hopefully, things I can show you this afternoon, and there are definitely things you can teach me. If there's something that's not clear, or it sounds like I'm just talking nonsense, or, you know, you're just interested then please do ask and by the end of the afternoon we'll all come out with a better appreciation of the language than when we came in.

Now I could carry on and give you another 100 minutes of slides, but we'd all be bored shitless in no time. Let's write some code, and we'll grow it from there.
--

* stack and heap - values vs references
* types -> templates create new types
* RAII
* performance guarantees - both in library specifications, but also in features (don't pay for what you don't use)
